
import type { FolderConfig } from './types';
import { Video, FileImage, UserSquare } from 'lucide-react';

export const folderConfig: FolderConfig[] = [
  {
    id: 'departing-testimonies-video',
    type: 'Departing Testimonies',
    subType: '(Video)',
    displayPath: '.../00_COMPLETED PROJECTS-VIDEOS',
    requiredFiles: ['mp4'],
    icon: Video,
    rules: [
      {
        pathPattern: "00_COMPLETED PROJECTS-VIDEOS",
        fileNameKeywords: ['departing', 'testimonies', 'testimony'],
      },
    ],
  },
  {
    id: 'transfer-video',
    type: 'Transfer Video',
    subType: '(Video)',
    displayPath: '.../EXPORTS or .../COMPLETED',
    requiredFiles: ['mp4'],
    icon: Video,
    rules: [
      { pathPattern: "01_TRANSFER VIDEO PROJECT FILE'S/EXPORTS" },
      { 
        pathPattern: "00_COMPLETED PROJECTS-VIDEOS",
        fileNameKeywords: ['transfer'],
      },
    ],
  },
  {
    id: 'departing-sign-pics',
    type: 'Departing Sign',
    subType: '(Pics)',
    displayPath: '.../06_DEPARTING.../...',
    requiredFiles: ['jpg', 'arw'],
    icon: FileImage,
    rules: [
      { pathPattern: "06_DEPARTING MISSIONARIES/PICTURES/00_EDITED~NAMED~FILTERED~FINAL", category: 'EDITED' },
      { pathPattern: "06_DEPARTING MISSIONARIES/PICTURES/01_JPEG", category: 'JPEG' },
      { pathPattern: "06_DEPARTING MISSIONARIES/PICTURES/01_jpg", category: 'JPEG' },
      { pathPattern: "06_DEPARTING MISSIONARIES/PICTURES/02_RAW*", category: 'RAW' },
      { pathPattern: "06_DEPARTING TESTIMONIES/PICTURES/00_EDITED~NAMED~FILTERED~FINAL", category: 'EDITED' },
      { pathPattern: "06_DEPARTING TESTIMONIES/PICTURES/01_JPEG", category: 'JPEG' },
      { pathPattern: "06_DEPARTING TESTIMONIES/PICTURES/01_jpg", category: 'JPEG' },
      { pathPattern: "06_DEPARTING TESTIMONIES/PICTURES/02_RAW*", category: 'RAW' },
      { pathPattern: "06_DEPARTING TESTIMONIE'S/PICTURES/00_EDITED~NAMED~FILTERED~FINAL", category: 'EDITED' },
      { pathPattern: "06_DEPARTING TESTIMONIE'S/PICTURES/01_JPEG", category: 'JPEG' },
      { pathPattern: "06_DEPARTING TESTIMONIE'S/PICTURES/01_jpg", category: 'JPEG' },
      { pathPattern: "06_DEPARTING TESTIMONIE'S/PICTURES/02_RAW*", category: 'RAW' },
      { pathPattern: "06_DEPARTING MISSIONARIES/* - PICS/00_EDITED~NAMED~FILTERED~FINAL", category: 'EDITED' },
      { pathPattern: "06_DEPARTING MISSIONARIES/* - PICS/01_JPEG", category: 'JPEG' },
      { pathPattern: "06_DEPARTING MISSIONARIES/* - PICS/01_jpg", category: 'JPEG' },
      { pathPattern: "06_DEPARTING MISSIONARIES/* - PICS/02_RAW*", category: 'RAW' },
    ],
  },
  {
    id: 'transfer-board-pics',
    type: 'Transfer Board',
    subType: '(Pics)',
    displayPath: '.../03_TRANSFER BOARD PICTURES/...',
    requiredFiles: ['jpg', 'arw'],
    icon: FileImage,
    rules: [
        { pathPattern: "03_TRANSFER BOARD PICTURES/00_EDITED~NAMED~FILTERED~FINAL", category: 'EDITED' },
        { pathPattern: "03_TRANSFER BOARD PICTURES/01_JPEG", category: 'JPEG' },
        { pathPattern: "03_TRANSFER BOARD PICTURES/01_jpg", category: 'JPEG' },
        { pathPattern: "03_TRANSFER BOARD PICTURES/02_RAW*", category: 'RAW' },
    ],
  },
  {
    id: 'titlow-park-ruston-pics',
    type: 'Titlow Park and Ruston',
    subType: '(Pics)',
    displayPath: '.../04_AIRPORT DAY/...',
    requiredFiles: ['jpg', 'arw'],
    icon: FileImage,
    rules: [
      { pathPattern: "04_AIRPORT DAY/PICTURES/*", category: 'EDITED' },
      { pathPattern: "04_AIRPORT DAY/PICTURES/*", category: 'JPEG' },
      { pathPattern: "04_AIRPORT DAY/PICTURES/*", category: 'RAW' },
      { pathPattern: "04_AIRPORT DAY/* - PICS/*", category: 'EDITED' },
      { pathPattern: "04_AIRPORT DAY/* - PICS/*", category: 'JPEG' },
      { pathPattern: "04_AIRPORT DAY/* - PICS/*", category: 'RAW' },
    ],
  },
  {
    id: 'airport-pics',
    type: 'Airport',
    subType: '(Pics)',
    displayPath: '.../04_AIRPORT DAY/...',
    requiredFiles: ['jpg', 'arw'],
    icon: FileImage,
    rules: [
      { pathPattern: "04_AIRPORT DAY/PICTURES/*", category: 'EDITED' },
      { pathPattern: "04_AIRPORT DAY/PICTURES/*", category: 'JPEG' },
      { pathPattern: "04_AIRPORT DAY/PICTURES/*", category: 'RAW' },
      { pathPattern: "04_AIRPORT DAY/* - PICS/*", category: 'EDITED' },
      { pathPattern: "04_AIRPORT DAY/* - PICS/*", category: 'JPEG' },
      { pathPattern: "04_AIRPORT DAY/* - PICS/*", category: 'RAW' },
    ],
  },
  {
    id: 'airport-vids',
    type: 'Airport',
    subType: '(Vids)',
    displayPath: '.../04_AIRPORT DAY/FOOTAGE',
    requiredFiles: ['mp4'],
    icon: Video,
    rules: [
      { pathPattern: "04_AIRPORT DAY/FOOTAGE/*/*" },
      { pathPattern: "04_AIRPORT DAY/FOOTAGE" },
      { pathPattern: "04_AIRPORT DAY/* - FOOTAGE/*" },
    ],
  },
  {
    id: 'arriving-sign-pics',
    type: 'Arriving Sign',
    subType: '(Pics)',
    displayPath: '.../05_TRANSFER MORNING/...',
    requiredFiles: ['jpg', 'arw'],
    icon: FileImage,
    rules: [
       { pathPattern: "05_TRANSFER MORNING/PICTURES/*", category: 'EDITED' },
       { pathPattern: "05_TRANSFER MORNING/PICTURES/*", category: 'JPEG' },
       { pathPattern: "05_TRANSFER MORNING/PICTURES/*", category: 'RAW' },
       { pathPattern: "05_TRANSFER MORNING/* - PICS/*", category: 'EDITED' },
       { pathPattern: "05_TRANSFER MORNING/* - PICS/*", category: 'JPEG' },
       { pathPattern: "05_TRANSFER MORNING/* - PICS/*", category: 'RAW' },
    ],
  },
  {
    id: 'meet-the-trainers-pics',
    type: 'Meet The Trainers',
    subType: '(Pics)',
    displayPath: '.../MEET THE TRAINERS',
    requiredFiles: ['jpg'],
    icon: FileImage,
    rules: [
      { pathPattern: "05_TRANSFER MORNING/MEET THE TRAINERS", category: 'PICS' },
    ],
  },
  {
    id: 'transfer-morning-vids',
    type: 'Transfer Morning',
    subType: '(Vids)',
    displayPath: '.../05_TRANSFER MORNING/FOOTAGE',
    requiredFiles: ['mp4'],
    icon: Video,
    rules: [
      { pathPattern: "05_TRANSFER MORNING/FOOTAGE/*/*" },
      { pathPattern: "05_TRANSFER MORNING/FOOTAGE" },
      { pathPattern: "05_TRANSFER MORNING/* - FOOTAGE/*" },
    ],
  },
  {
    id: 'missionary-requests-pics',
    type: 'Missionary Requests',
    subType: '(Pics)',
    displayPath: 'N/A',
    requiredFiles: ['jpg', 'arw'],
    icon: UserSquare,
    rules: [],
  },
];
